### PR TITLE
fix: add accessor function types in MemberDescription

### PR DESCRIPTION
**Pull request by Shanks0224**
Joint debugging with @zhenweijin

### CODE REVIEW

**Comment by xujuntwt95329** [comment]
@Shanks0224 Is there any test cases to cover this fix?

**Comment by Shanks0224** [comment]
> @Shanks0224 Is there any test cases to cover this fix?

```
interface I {
    _row?: number;

    set row(val: number);

    get row(): number;
}

class A implements I {
    _row: number;

    constructor(row: number) {
        this._row = row;
    }

    get row() {
        return this._row;
    }

    set row(val: number) {
        this._row = val;
    }
}

export function test() {
    const a: A = new A(1);
    const i: I = a;
    i.row = 5;
}
```

**Comment by xujuntwt95329** [comment]
> > @Shanks0224 Is there any test cases to cover this fix?
> 
> ```
> interface I {
>     _row?: number;
> 
>     set row(val: number);
> 
>     get row(): number;
> }
> 
> class A implements I {
>     _row: number;
> 
>     constructor(row: number) {
>         this._row = row;
>     }
> 
>     get row() {
>         return this._row;
>     }
> 
>     set row(val: number) {
>         this._row = val;
>     }
> }
> 
> export function test() {
>     const a: A = new A(1);
>     const i: I = a;
>     i.row = 5;
> }
> ```
> 
> When there is an optional field in the interface and this field is operated on through the accessor, the compiler will report an error.

Can we add this into test cases?

**Comment by Shanks0224** [comment]
> > > @Shanks0224 Is there any test cases to cover this fix?
> > 
> > 
> > ```
> > interface I {
> >     _row?: number;
> > 
> >     set row(val: number);
> > 
> >     get row(): number;
> > }
> > 
> > class A implements I {
> >     _row: number;
> > 
> >     constructor(row: number) {
> >         this._row = row;
> >     }
> > 
> >     get row() {
> >         return this._row;
> >     }
> > 
> >     set row(val: number) {
> >         this._row = val;
> >     }
> > }
> > 
> > export function test() {
> >     const a: A = new A(1);
> >     const i: I = a;
> >     i.row = 5;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When there is an optional field in the interface and this field is operated on through the accessor, the compiler will report an error.
> 
> Can we add this into test cases?

This work has not been finished yet and needs to be modified on the back end. I think we can add the case after the back-end code has been modified.

**Review by zhenweijin — COMMENTED** [review]
LGTM

**Pull request closed without merging**
